=== Diego0rrill0/LMSGI-1er-a-o-/UT3/gym.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="actividades">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="actividad" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="start_date" type="xs:date"/>
              <xs:element name="sesions">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="duration_session" type="xs:positiveInteger"/>
                    <xs:element name="week_frecuency" type="xs:positiveInteger"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="anio" type="xs:gYear" use="required"/>
            <xs:attribute name="level">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="child"/>
                  <xs:enumeration value="adults"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="code">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="A\d{2}"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="intensity">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="soft"/>
                  <xs:enumeration value="moderate"/>
                  <xs:enumeration value="hard"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Diego0rrill0/LMSGI-1er-a-o-/UT3/gymXSD.xml
<actividades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="gym.xsd">
  <actividad anio="2015" level="adults" code="A01" intensity="soft">
    <start_date>2015-01-15</start_date>
    <sesions>
      <duration_session>45</duration_session>
      <week_frecuency>3</week_frecuency>
    </sesions>
  </actividad>
  <actividad anio="2015" level="child" code="A02" intensity="moderate">
    <start_date>2015-01-08</start_date>
    <sesions>
      <duration_session>45</duration_session>
      <week_frecuency>3</week_frecuency>
    </sesions>
  </actividad>
  <actividad anio="2015" level="adults" code="A03" intensity="hard">
    <start_date>2015-01-15</start_date>
    <sesions>
      <duration_session>60</duration_session>
      <week_frecuency>2</week_frecuency>
    </sesions>
  </actividad>
  <actividad anio="2015" level="adults" code="A04" intensity="soft">
    <start_date>2015-01-15</start_date>
    <sesions>
      <duration_session>45</duration_session>
      <week_frecuency>2</week_frecuency>
    </sesions>
  </actividad>
  <actividad anio="2015" level="adults" code="A05" intensity="soft">
    <start_date>2015-01-15</start_date>
    <sesions>
      <duration_session>45</duration_session>
      <week_frecuency>2</week_frecuency>
    </sesions>
  </actividad>
  <actividad anio="2015" level="adults" code="A06" intensity="soft">
    <start_date>2015-02-15</start_date>
    <sesions>
      <duration_session>45</duration_session>
      <week_frecuency>2</week_frecuency>
    </sesions>
  </actividad>
</actividades>
